import { Montserrat } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";
import Header from "@/components/header/Header";
import { Providers } from "@/components/helper/Providers";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export function generateStaticParams() {
//    return users.map((user) => ({ lng }));

// }

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <Providers>
          <div className={styles.container}>
            <div className={styles.top}>
              <Header />
            </div>
            <main className={styles.page}>{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
